# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Show Xcode version
        run: xcodebuild -version
      - name: List Device Types
        run: xcrun simctl list devicetypes

      - name: List Runtimes
        run: xcrun simctl list runtimes

      - name: List Devices
        run: xcrun simctl list devices
      - name: Resolve Swift Packages
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project Testapp.xcodeproj
      - name: Show Destinations JSON
        run: |
          xcodebuild \
           -project Testapp.xcodeproj \
           -scheme Testapp \
           -showdestinations -json
           
      - name: Show Important Build Settings
        run: |
         xcodebuild \
         -project Testapp.xcodeproj \
         -scheme Testapp \
         -showBuildSettings | egrep \
          "PRODUCT_TYPE|SUPPORTED_PLATFORMS|TARGETED_DEVICE_FAMILY|SDKROOT|IPHONEOS_DEPLOYMENT_TARGET|PRODUCT_BUNDLE_IDENTIFIER"
      - name: Build
        run: |
           xcodebuild \
            -project Testapp.xcodeproj \
            -scheme Testapp \
            -sdk iphonesimulator \
             clean build
