# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Resolve Swift Packages
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project Testapp.xcodeproj
      - name: Show Destinations JSON
        run: |
          xcodebuild \
           -project Testapp.xcodeproj \
           -scheme Testapp \
           -showdestinations -json
           
      - name: Show Important Build Settings
        run: |
         xcodebuild \
         -project Testapp.xcodeproj \
         -scheme Testapp \
         -showBuildSettings | egrep \
          "PRODUCT_TYPE|SUPPORTED_PLATFORMS|TARGETED_DEVICE_FAMILY|SDKROOT|IPHONEOS_DEPLOYMENT_TARGET|PRODUCT_BUNDLE_IDENTIFIER"
      - name: Build
        run: |
           xcodebuild \
            -project Testapp.xcodeproj \
            -scheme Testapp \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
             clean build
      - name: Collect App
        run: |
         mkdir -p artifacts

         APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData \
         -path "*/Build/Products/Debug-iphonesimulator/Testapp.app" \
         | head -n 1)

         echo "Found app at: $APP_PATH"

         if [ -z "$APP_PATH" ]; then
         echo "Testapp.app not found!"
         exit 1
         fi

         cp -R "$APP_PATH" artifacts/

         ls -R artifacts

      - name: Upload Simulator App
        uses: actions/upload-artifact@v4
        with:
         name: Testapp-Simulator
         path: artifacts
